# ba0fde3d-bee7-4307-b97b-17d0d20aff50
[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Runtime",
  "org.fedoraproject.Anaconda.Modules.Network",
  "org.fedoraproject.Anaconda.Modules.Payloads",
  "org.fedoraproject.Anaconda.Modules.Security",
  "org.fedoraproject.Anaconda.Modules.Services",
  "org.fedoraproject.Anaconda.Modules.Storage",
  "org.fedoraproject.Anaconda.Modules.Users",
  "org.fedoraproject.Anaconda.Modules.Localization",
  "org.fedoraproject.Anaconda.Modules.Timezone"
]
disable = [
  "org.fedoraproject.Anaconda.Modules.Subscription"
]

[customizations.installer.kickstart]
contents = """
%post --erroronfail --log=/root/anaconda-post.log
bootc switch --mutate-in-place --transport registry <IMAGE_SIGNED> <UPDATE_IMAGE_REF>

%end
"""
